# Generated by Django 3.2.13 on 2022-06-29 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exonStart', models.IntegerField()),
                ('exonStop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_userid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WmrglVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UCSC_browser_update_date', models.DateTimeField()),
                ('wmgl_version_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_tracker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usertracker')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coding', models.CharField(max_length=3)),
                ('strand', models.CharField(max_length=1)),
                ('chromosome', models.CharField(max_length=255)),
                ('cdsStart', models.IntegerField()),
                ('cdsStop', models.IntegerField()),
                ('search_timestamp', models.DateTimeField()),
                ('exon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exon')),
                ('upload_id', models.ManyToManyField(to='app.Upload')),
                ('wmrgl_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wmrglversion')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=200)),
                ('transcript_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transcript')),
            ],
        ),
    ]
