# Generated by Django 4.0.5 on 2022-07-05 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='transcript_id',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='exon_id',
        ),
        migrations.AddField(
            model_name='exon',
            name='transcript_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.transcript'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcript',
            name='gene_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.gene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_genes',
            field=models.ManyToManyField(to='app.gene'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upload',
            name='user_tracker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usertracker'),
        ),
    ]
