# Generated by Django 4.0.5 on 2022-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_gene_transcript_id_remove_transcript_exon_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='chromosome',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='search_timestamp',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
