# Generated by Django 4.0.5 on 2022-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gene_chromosome_gene_search_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='cdsStart',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='cdsStop',
            field=models.IntegerField(null=True),
        ),
    ]
