# Generated by Django 4.0.5 on 2022-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_exon_transcript_id_alter_transcript_gene_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exon',
            name='exonStop',
            field=models.IntegerField(null=True),
        ),
    ]
